# Generated by Django 4.0.3 on 2022-07-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_password_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userDB',
        ),
    ]
